# Generated by Django 4.2.26 on 2026-01-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id_autobus', models.AutoField(primary_key=True, serialize=False)),
                ('economico', models.CharField(max_length=50)),
                ('no_obra', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('seams', models.CharField(blank=True, max_length=50, null=True)),
                ('placas', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'autobusTabla',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conductorTabla',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'proveedorTabla',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cargo',
            fields=[
                ('id_tipo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_cargoTabla',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Dano',
            fields=[
                ('id_tipo_dano', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_danoTabla',
            },
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('carpeta_base', models.CharField(max_length=100)),
                ('carpeta_evidencia_inicial', models.URLField()),
                ('carpeta_evidencia_final', models.URLField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_acc', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('comentarios_cierre', models.TextField(blank=True, null=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('EN_REPARACION', 'En reparación'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=15)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.autobus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.conductor')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ACC.proveedor')),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.tipo_cargo')),
                ('tipo_dano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.tipo_dano')),
            ],
            options={
                'db_table': 'accidenteTabla',
            },
        ),
    ]
