# Generated by Django 4.2.26 on 2026-01-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id_autobus', models.AutoField(primary_key=True, serialize=False)),
                ('economico', models.CharField(max_length=50)),
                ('no_obra', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('seams', models.CharField(blank=True, max_length=50, null=True)),
                ('placas', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'autobusTabla',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conductorTabla',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'proveedorTabla',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cargo',
            fields=[
                ('id_tipo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_cargoTabla',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Dano',
            fields=[
                ('id_tipo_dano', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_danoTabla',
            },
        ),
    ]
