# Generated by Django 4.2.26 on 2026-01-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('carpeta_base', models.CharField(max_length=100)),
                ('carpeta_evidencia_inicial', models.URLField()),
                ('carpeta_evidencia_final', models.URLField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_acc', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('comentarios_cierre', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('EN_REPARACION', 'En reparación'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=15)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.autobus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.conductor')),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.tipo_cargo')),
                ('tipo_dano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACC.tipo_dano')),
            ],
            options={
                'db_table': 'accidenteTabla',
            },
        ),
    ]
