# Generated by Django 4.2.26 on 2026-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='carpeta_evidencia_final_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
