# Generated by Django 4.2.26 on 2026-02-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACC', '0002_accidente_carpeta_evidencia_final_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidente',
            old_name='carpeta_evidencia_final_id',
            new_name='carpeta_evidencia_inicial_id',
        ),
    ]
